sudo: required
services:
  - docker

before_install:
  - docker build -t dockerized/docker-tutorial -f Dockerfile.dev .

script:
  - docker run -r CI=true dockerized/docker-tutorial npm run test
language: generic
