version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING= true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - /app/node_modules
      - .:/app
